# This file configures the workflows to trigger in our Prow jobs.
# see https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py
#
# The testWorkerImage should be the same for all workflows.
python_paths:
  - kubeflow/mpi-operator/py
workflows:
  - name: e2e-mpi
    py_func: kubeflow.mpi-operator.create_e2e_workflow.create_workflow
    job_type:
      - periodic
      - presubmit
      - postsubmit

    
