# This file configures the workflows to trigger in our Prow jobs.
# see https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py
#
# The testWorkerImage should be the same for all workflows.
python_paths:
  - kubeflow/mpi-operator/py
workflows:
  - tekton_run: kubeflow/mpi-operator/tests/test-nb-pipeline-run.yaml 
    name: mpi-e2e-test
    job_types:
    - periodic
    - presubmit
    - postsubmit 
